[project]
name = 'healthchain'
description = 'Decentralized health record system on Stacks blockchain'
authors = []
telemetry = true
cache_dir = './.cache'

[contracts.healthchain]
path = 'contracts/healthchain.clar'
clarity_version = 3
epoch = 3.0

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = false
callee_filter = false
